[InternetShortcut]
URL=http://mercury.pr.erau.edu/~siewerts/cec450/code/Feasibility/Makefile
IDList=
HotKey=0
IconFile=C:\Users\Tim\AppData\Local\Mozilla\Firefox\Profiles\hult4y9m.default\shortcutCache\Rfc6ezEUSPMlAD9Tmo2IQw==.ico
IconIndex=0
